### ISSUE TITLE
Publish the list of hypotheses in a more readable and nice way

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#100]
Goal: Currently the different hypotheses are in the master spreadsheet, and are very messy. They are suitable for us internally, but not to show external stakeholders. 

Can we publish them in a clean and nice way somewhere? 
I don't know how to make a table in a github page, but that might be a solution. 

Thoughts @secretrobotron ?

**Comment by secretrobotron** [comment]
I hesitate to put a lot of effort into publishing these, since they're far less important than content of the modules that the hypotheses led us to. 

 think that discussing a set of hypotheses (e.g. https://github.com/MozillaFoundation/digital-skills-observatory/issues/97) for each intervention would work better, while keeping the spreadsheet around for sketching out those ideas.

Actually, as we develop things, I think it would be more useful to see which hypotheses we tested (and are testing currently) somewhere, because sometimes they will cascade.

**Comment by lauradereynal** [comment]
Agreed. thanks for the feedback ! we can publish as we go.

**Comment by secretrobotron** [comment]
Let's keep this open so we can remember to do it after the first intervention!

**Comment by chanditome** [comment]
Issue #100 looking good! Clearly a sign that things are taking shape.

**Comment by secretrobotron** [comment]
@chanditome yes! Thanks for your input :+1: :dancer: .

**Comment by secretrobotron** [comment]
We've moved on from this approach, and have published our intent elsewhere, I think.

@LauraReynal, still want to pursue this?
