### ISSUE TITLE
Collect, organize & finalize the content for the Quiztorial app.

### ISSUE THREAD

**Issue by flukeout** [MozillaFoundation/digital-skills-observatory#151]
**To-Do**
- ~~@secretrobotron Summarize and organize findings from [this doc](https://mozilla-foundation-research.herokuapp.com/dso-nairobis-first-intervention/)~~ (just look below)
- Work done in the [Gamification Document](https://docs.google.com/document/d/1SXI7P4xRoG4AtJ4-Cpct8n--IfQZXSy_aWfMGKys22s/edit?ts=5722854c)
- Work done by the Jisort team

**Goal**
- Produce one reference doc where we have the content we want to teach, grouped by topic area with a list of specific skills for each one.

**Comment by secretrobotron** [comment]
cc @LauraReynal let's organize findings in a summary so that this group can use them. Would be good for @chadsansing as well.

**Comment by secretrobotron** [comment]
Compiling a list of topics/ideas to cover.

#### Tutorials

##### Connectivity
- Help users understand how Wi-Fi works, and encourage use 👍 
- Usher users toward the Cellular Data Usage panel in Android
- List useful shortcodes to access telco services :+1: 
- Explain data bundles, their relationship with airtime, and options for buying/selling

##### Phone Usage
- Explain why memory is running low and what users can do about it
- Help users troubleshoot SD card problems
- Explain and demonstrate settings and simple apps (e.g. alarms, location settings, etc.) 👍 

##### Apps
- Illustrate various methods to get apps and content (Play Store, Bluetooth, Flash Share, other apps, etc.)
- Encourage app discovery and installation through the Play Store and app safety awareness (permissions, reviews, # of installs) 👍 
- Show users how to update apps and how to resolve problems with that process when they arise (e.g. got app over Flash Share, so it doesn't update through Play Store)

##### Internet Usage
- Help users understand and use popular social media platforms
- Help users understand the process of making an account (not sure of whether or not we should fully explore online identity) 👍 
- Show users which apps easily consume a lot of data and what can be done about it
- List useful terms (e.g. download, Internet, data, Safaricom, M-Pesa, account, etc.)
- Help people understand what is the internet and how to use it 👍 

#### Icons
- Connectivity: Wi-Fi, Bluetooth, cell
- Settings: Location, Hotspot, Settings (app)
- Apps: Play Store, SIM Toolkit, Downloads

cc @LauraReynal @Obadha @xelawafs I tried to cover the stuff you had mentioned previously. Anything else you would add or recategorize? The icons section is sorely lacking; instead of covering all of Material Design, I think we can choose specific icons that users will face, and do a great job of documenting them.

**Comment by secretrobotron** [comment]
@LauraReynal just had a really good point about being "proactive". Maybe we can have topics that will help users opportunistically. e.g.,
- Just downloaded a huge file. Did you know that impacts your data usage significantly? What app did it?
- A (trusted) open Wi-Fi appeared! Connect to it to avoid data usage and download apps.

Those aren't great examples, but that's the idea. Anything else we can think of?

**Comment by lauradereynal** [comment]
I think we should prioritize the different things you noted for the tutorials. SO, I added some 👍 on the ones that seems to be the most important. Can you guys also add some +1s ?

**Comment by LauraReynal** [comment]
Other proactive examples: 

* Your phone crashed because of a problem with

**Comment by lauradereynal** [comment]
Feature idea: we were originally thinking about drawing / highlighting an issue on the screen. Could we explore this idea? 
- Click that button to take a screenshot 
- Circle in red the part that gives you trouble 

–– I am mainly trying to make sure we leverage the smartphone form factor (touch screen, apps, GPS, Wifi, ...)

Thoughts?

**Comment by secretrobotron** [comment]
> we were originally thinking about drawing / highlighting an issue on the screen

Would be worth wireframing in more detail, IMO.

**Comment by lauradereynal** [comment]
One of our research [questions](https://github.com/MozillaFoundation/digital-skills-observatory/blob/master/questions.md) is about sheng / emoticons and colloquial languages. Can we try to use this in our app so that we can see how it affects people ? 
Im not sure if that's a good idea or not. We could also save it for the next prototype

**Comment by flukeout** [comment]
Hey great work on this so far, I'll integrate it into the wireframes today and see how it's feeling. I'm worried that the category aren't super clear maybe, but we're also exploring some imagery to help people out there. That's also where slang / colloquial langs might help too as @LauraReynal mentioned.

And yeah, I'll take a crack at wireframing a 'suggested topic' based on our best guess of what's going on at that time for the user.

**Comment by flukeout** [comment]
Here's an attempt at using some imagery to help user differentiate between those topics...

![image](https://cloud.githubusercontent.com/assets/25212/15412073/a488dfa0-1dd9-11e6-97b3-cad471bde77d.png)

**Comment by TheBonface** [comment]
@flukeout that's nice I like how you have designed the categories , it is clear and precise

**Comment by lauradereynal** [comment]
@flukeout love where this is going !! 😸 
I wonder how we make sure we use sheng and colloquial language? Should we work on the copy first and then change potentially difficult words or should we just start in sheng right now ?

**Comment by secretrobotron** [comment]
Moving this along and working on some content in #191 and in https://docs.google.com/document/d/1PMK72_jRepGkhtKoK1wHv4NPwnBhub9yjK7pIwVzeTM/edit#. Would be great to have some help with language once it's done. I think it will be less relevant in English.
