### ISSUE TITLE
Create DSO mid-study Report for Gates Foundation

### ISSUE THREAD

**Issue by lauradereynal** [MozillaFoundation/digital-skills-observatory#169]
Goal: We are comitted to submit a mid-research review for Gates as a deliverable for this project. 

Idea: combine all the blog posts into one document. 
We will need to add interview data and the results from other interventions

Team: @secretrobotron @JoashMango @DuncanGW 
With help from @metaphorista @KalpanaSimhan 

To do: 
- [x] Write the summary of the interviews 
- [x] Write the summary of the interventions 
- [x] Write the the early research insights 
- [x] Write the summary of our prototyping experiences (Jisort + Hackathon)
- [x] Write something about the community and Open Research
- [x] Summarize insights from the quantitative data collection 
- [x] Summarize insights from the comparative treatment / control analysis
- [x] Code and summarize the qualitative information in the interviews
- [x] Copy copy copy 
- [x] Add a section with questions and things to decide 
- [x] Images and format 
- [x] Share out with invitation to comment

**Comment by lauradereynal** [comment]
@metaphorista do you know if we have a deadline ? We said June or July ?

**Comment by secretrobotron** [comment]
Proposal:
- copy style from mzl.la/dso
- host as website on mzl.la/dso-mid-report or similar
- write introduction and project status summary
- select snippets from blog thus far
- selection of emerging participants profiles
- point-form summary of findings from intervention 1
- point-form summary of insights from phone/interview data
- lots of pictures and graphics (e.g. path of disillusionment from intervention 1)
- next steps

Too much?

cc @LauraReynal

**Comment by lauradereynal** [comment]
That works well for me. 

What's our deadline? June 27th? (day before we take off to the July field trip) 

@metaphorista and @kalpanaSimhan what do you think? Did we forget anything that we are committed to?

**Comment by KalpanaSimhan** [comment]
@LauraReynal @secretrobotron we don't have any deadline to meet.  So you can write the report once you feel you've reached the midpoint of the study, and have strong data and insights to report.

Also, and @metaphorista correct me if I'm wrong, but from the results tracker it seems to me the midpoint report is not something we're required to do as per the terms of the grant (i.e. it isn't marked with an "X" so we don't have to report on it to Gates). Do you guys have the results tracker document?

As for what to include in the report, in the results tracker, we say the mid and final reports will be a discussion of "findings, insights, opportunities, and lessons learned on how smartphones affect the adoption and use of DFS amongst first-time users in Kenya." Your audience is described as "all key stakeholders." All of this is very broad and we don't want to do the report just because we said we would, we want it to have impact. So rather than starting with the content of the report, I suggest we start by defining the purpose and audience for the report more specifically.

**Comment by lauradereynal** [comment]
Status update: this is on hold until we decide if we run a workshop in July or not.

**Comment by secretrobotron** [comment]
Should be done for first week of September.

**Comment by lauradereynal** [comment]
We are currently in the middle of this work, and I agree with @KalpanaSimhan 's point about not doing a report for the sake of the report. 

@secretrobotron what do you think of this audience and purpose: 
- **Gates Foundation PO and the Financial Services for the poor department**: Follow the progress of the investment and rectify, advise for the work remaining, to make sure it's still aligned with their needs. 
- **Mozilla staff and community + Project team**: understand what we have, what we are missing and remaining work. 
- **DSO informal advisors group**: Provide insights, challenge our thinking, follow the progress of the project. Same goals as fostering an Open Research community.

**Comment by lauradereynal** [comment]
Oh WOW we did all the above, and more than our scope of work. 

Thanks to everyone who helped and reviewed. It was an excellent exercice for us.
