### ISSUE TITLE
Investigate client-side data collection methods

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#22]
We need to collect data from participants' browsers (with consent). Maybe we use a Firefox addon (mobile?) to help.

@JoashMango & Duncan, do you mind providing a description of what you need? That will help me start investigating with the help of the Firefox community.

(btw, could be a great opportunity for volunteers.)

**Comment by benrito** [comment]
Obvious (maybe dumb) question—what if they don't use a Firefox browser? Won't this give us a biased/limited sample?

**Comment by secretrobotron** [comment]
@benrito yeah, definitely. I'm not sure what the deployment plan is for software on phones. The best we can do is make Firefox the **default** browser, but probably not stop them from trying another if they want to. Beyond that, we'd be restricting their usage.

It's probably best to have tools that can capture data from any browser.

**Comment by DuncanGW** [comment]
Point to keep in mind, we do not want to change respondents behaviors i.e the tools/apps they use on their smartphone and perceptions toward different tools. 
on the point of the browser, we definitely don't want to limit them to a specific browser . We wanted to know based on Mozilla tools/ addons can we capture phone usage in an efficient way? a tool that capture data from any browser can be cool. 
On the first screening interview we will definitely know what browser are commonly used.

We are consulting with our IT team if we get an app that can help us capture the phone usage data in the background.
*_Our desire is a tool that can run the in the background on the phone and capture phone usage without affecting the preponderant behavior. This will be used to compliment the data that we will get through interviews with respondents. *_

Our consent paper should be able to suffice for any confidential data that we will be collecting from the respondents.

**Comment by lauradereynal** [comment]
What is the update on this one based on our phone call yesterday ?

**Comment by secretrobotron** [comment]
I'm doing some outreach/fact-finding to see what's possible here.

**Comment by benrito** [comment]
Did anyone give feedback on Adam’s DSO data collection plan?

https://docs.google.com/document/d/1Xb6mSjDqlFMVWKsMO1Sc3YbYY_vsKaXPRUiHMQFsMBE/edit?ts=567965f3 https://docs.google.com/a/mozillafoundation.org/document/d/1Xb6mSjDqlFMVWKsMO1Sc3YbYY_vsKaXPRUiHMQFsMBE/edit?usp=sharing_eid&ts=567965f3

**Comment by secretrobotron** [comment]
Yeah, thanks for the reminder, @benrito.

**Comment by DuncanGW** [comment]
@LauraReynal and @secretrobotron based on our last call, we mentioned that we have investigated different methods or apps of getting respondents data on phone usage. But the challenge is the apps or the methods might affect the respondents behavior for instance if an app on the phone shows the respondents how he/she spend time on the phone might make the respondent to change his/her behavior. We are thinking if we can select a few of the respondent and have such phone usage apps after recruiting and appreciating their trust and openness. So that we don't affect all the respondents.
Secondly we are thinking of using different data sets to enable us capture the phone usage data i.e. mobile money transactions/statements can tell us how the respondents uses DFS. The Data Usage feature on android can help us capture the amount of data used by the phone and even to specific apps. 
Let continues discussing even during the boot camp and evaluate what methods are viable that we can use.

**Comment by lauradereynal** [comment]
I believe this can be closed. 
Re-open if im wrong
