### ISSUE TITLE
Come up with a name for the bot

### ISSUE THREAD

**Issue by secretrobotron** [MozillaFoundation/digital-skills-observatory#261]
It can't be called DSO Bot anymore. It needs a persona!

Let's come up with the following—maybe one for each actor:
- Name
- Age
- Gender
- Location
- Small backstory
- Favourite animal and flavour of ice cream

**Comment by secretrobotron** [comment]
cc @Josiahma1 @Uwanja @denomain

**Comment by Josiahma1** [comment]
The age can preferably be in between 22 years to 28. We ca also pick locations based on the actor's familiarity with a location relative to the participant's location. Let me think of a backstory and get back. we can also rethink this 'Favourite animal and flavour of ice cream' to something more locally relevant.

**Comment by Uwanja** [comment]
Name: Sterro/Stero a corruption of the word starring in English. In sheng it means someone who is brave and mostly to confront difficult situations. For this case the difficulty could be the queries posed by the members of the group.

Age: 27...because it is divisible by the 3 actors :smile: 
Gender: Male
Location: Some
Small backstory: When we were kids we used to watch movies that always had an almost similar plot. There was the villain and the starring. The starring(sterro) according to us was the guy or lady that would emerge the winner or hero at the end of the movie. 
Favorite animal and flavor of ice cream: 
Animal Lion (bravery) 
Ice Cream: Vanilla

**Comment by TheBonface** [comment]
Name : stadi  , a Swahili word which is used to describe a professional , or someone good at his or her work . so the bot will be stadi {good at answering the problems pushed to it }

Age: 25- 29  because that's when most people start to put their life's in order. They tend to carry out tasks or responsibilities to their level best 

Location :  Kawangware , Madhare , Manyatta in Kisumu , or Nyalenda , or any hood . 
Small backstory : Stadi is the character who , has lot's of skills  gained from attending different hackathons, he/she works hard to get everything right , smashing each and every opportunity that he/she gets.  The character works tirelessly and most of the people in the hood turns to him/her for the tech advices, He/she manages to carryout most computer related , work coz the character never says no to any challenge , he/she gains a lot of experiences from the problems and new challenges brought to his/her attention  over the years.

Favorite animal : Cheetah , because the character understand the importance of speed and precision (it's hood , anyone can do anything , your speed and precision determines your next client)
Ice cream :  The one that tastes like toothpaste , I forgot the name

**Comment by AI-DennisNdegwa** [comment]
Mjanja meaning. "Bright one" or "smart one".

Age: 25 
Gender: Male
Location: CBD
Small backstory: Mjanja grew up in Nairobi where he was introduced to computers by his mother who was a secretary at company X. When he cried, his mama would give him an old mouse or keyboard to play with. He would only sleep under the influence of humming sounds of the servers or under the fading sounds of a dying UPS. He later grew up to love android phones and the internet. Mjanja still sleeps in a server room with some UPSes to give him comfort. During the day he passes off as a normal high school teacher. Teacher with a dark secret!

**Comment by Josiahma1** [comment]
Ulemsee/the man- meaning someone who knows a lot of stuff

Gender Male
Age 24
Location Eastlands 

He considers himself someone who has the solution to everything. Despite having the know, it all attitude he can bail someone out of a  problem, therefore, a problem solver. The story behind this can be based on someone with a street appeal who has the answer to everything.This is also a trending name thus it would make people intrigued to find out about the ideas he has.

**Comment by lauradereynal** [comment]
Awesome work team 👍 

My 3 favorite names are: Mjanja, Stadi, Sterro 

I have reservations about Ulemsee because of it's meaning. It's very male-focus "the man who knows everything".

**Comment by WinnieMakokha** [comment]
Name: _Kastomer Kare_ 
Meaning: contorted from the phrase "customer care". Pronounced same way as customer care.
Location: Anywhere in the Kenyan Republic
Age: 25-28
Gender: Male and Female
Small Backstory: Everytime you interact with both amateur and experienced  mobile phone users in Kenya and you ask them about something on their phone that needs a solution they will almost always give you a reflex response "ebu pigia customer care" (translate: try calling customer care and inquire from them).
This is especially the case with regards MPesa/Mshwari and any other DFS services offered through the mobile phone platform. 
Even the physical shops of either phone vendors or mobile phone service providers like Safaricom, Airtel and Orange are normally referred to as customer care.  it is an easily identifiable phrase. 
The gender is both male and female because typically customer care agents are both:-)

Favourite animal: Eagle

Ice cream: Vanilla.

*i have reservations about favourite icecream as a way to identify the bot actors. Most people dont indulge in icecream often but would easily identify with favourite dishes/food e.g. Ugali nyama wetfry/pilau/chapati/githeri

**Comment by JoashMango** [comment]
I do agree with Laura on ulemsee to me doesn't take into consideration both
gender its more of male focus. It won't sound good with the rest of
participants.

Thanks

**Comment by nao07** [comment]
I really like Mjanja and Sterro. Sounds interesting.

**Comment by AI-DennisNdegwa** [comment]
Another suggestion 
    Name : Beshte (sheng word meaning "friend")
    Age : 25
    Gender : Male
    Location : Nairobi

**Comment by secretrobotron** [comment]
Final suggestion is _Sterro Mjanja_. We will fuse their profiles.

**Comment by secretrobotron** [comment]
Final:

##### Name

Sterro Mjanja

##### Gender

Male

##### Age

27

##### Background

Sterro got his name from parents who were fans of movies featuring stereotypical heroes and villains. At an early age, his parents introduced him to these movies, where he adopted the Sterro persona to fit his name.

In Nairobi he was introduced to computers by his mother. She was a secretary at company Postal Corporation of Kenya and had early exposure to the advent of personal computing in Kenya. As a result, Sterro would only sleep under the influence of humming sounds of old computer fans as a child.

Later, Sterro grew to love Android phones and the internet, and familiarized himself with building his own websites. Now, he normally works as a high school teacher, but has decided to devote himself to teaching people how to use their smartphones and the internet wisely.

##### Favourite Things

**Ice cream**: Vanilla
**Animal**: Lions, because they’re brave
**Technology**: HTML and JavaScript because he loves building websites
**Hobbies**: Action and romantic comedy movies, traveling around Kenya to teach about technology, and practicing self-motivation
