### ISSUE TITLE
capturing DFS e.g. M-Pesa using the new email statements feature

### ISSUE THREAD

**Issue by DuncanGW** [MozillaFoundation/digital-skills-observatory#78]
To track it.

**Comment by lauradereynal** [comment]
Hey Duncan, can you provide some details here? what is the new email statements feature?

**Comment by Amuti** [comment]
Hey @LauraReynal for the Mpesa email statement feature what the user does is use the short code *234# to register their email address for the service via their handset
The statements are sent every 5th of the month to their email
This is interesting since the banks still charge for these monthly statements
I do agree this is a feature to track for DFS if we think in the lines on how these statements could be presented(data visualized)  in a way that the user can tell/understand their spending habits?

**Comment by lauradereynal** [comment]
That's awesome. Thanks for the explanation @Amuti

**Comment by secretrobotron** [comment]
@DuncanGW are we tracking this now?

**Comment by secretrobotron** [comment]
I'm pretty sure @DuncanGW's been doing this since he filed the issue. Closing.
